/*
 * This file is part of the coreboot project.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation; version 2 of
 * the License.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */

#ifndef _PCH_GPIO_H
#define _PCH_GPIO_H

#include <soc/gpe.h>
#include <soc/gpio.h>

/* Pad configuration in ramstage */
static const struct pad_config gpio_table[] = {

	/* ------- GPIO Community 0 ------- */

	/* ------- GPIO Group GPP_A ------- */
	/* GPP_A0 - RCIN# */
	PAD_CFG_NF_BUF_TRIG(GPP_A0, NONE, PLTRST, NF1, TX_DISABLE, OFF),
	/* GPP_A1 - LAD0 */
	PAD_CFG_NF_BUF_TRIG(GPP_A1, 20K_PU, PLTRST, NF1, NO_DISABLE, OFF),
	/* GPP_A2 - LAD1 */
	PAD_CFG_NF_BUF_TRIG(GPP_A2, 20K_PU, PLTRST, NF1, NO_DISABLE, OFF),
	/* GPP_A3 - LAD2 */
	PAD_CFG_NF_BUF_TRIG(GPP_A3, 20K_PU, PLTRST, NF1, NO_DISABLE, OFF),
	/* GPP_A4 - LAD3 */
	PAD_CFG_NF_BUF_TRIG(GPP_A4, 20K_PU, PLTRST, NF1, NO_DISABLE, OFF),
	/* GPP_A5 - LFRAME# */
	PAD_CFG_NF_BUF_TRIG(GPP_A5, NONE, PLTRST, NF1, RX_DISABLE, OFF),
	/* GPP_A6 - SERIRQ */
	PAD_CFG_NF_BUF_TRIG(GPP_A6, NONE, PLTRST, NF1, NO_DISABLE, OFF),
	/* GPP_A7 - GPIO */
	PAD_CFG_GPO(GPP_A7, 1, DEEP),
	/* GPP_A8 - GPIO */
	PAD_CFG_GPO(GPP_A8, 1, PLTRST),
	/* GPP_A9 - CLKOUT_LPC0 */
	PAD_CFG_NF_BUF_TRIG(GPP_A9, 20K_PD, PLTRST, NF1, RX_DISABLE, OFF),
	/* GPP_A10 - CLKOUT_LPC1 */
	PAD_CFG_NF_BUF_TRIG(GPP_A10, 20K_PD, PLTRST, NF1, RX_DISABLE, OFF),
	/* GPP_A11 - GPIO */
	PAD_CFG_GPO(GPP_A11, 1, DEEP),
	/* GPP_A12 - GPIO */
	PAD_CFG_GPO(GPP_A12, 0, DEEP),
	/* GPP_A13 - GPIO */
	PAD_CFG_GPO(GPP_A13, 0, DEEP),
	/* GPP_A14 - GPIO */
	PAD_CFG_GPO(GPP_A14, 0, DEEP),
	/* GPP_A15 - GPIO */
	PAD_CFG_GPO(GPP_A15, 0, DEEP),
	/* GPP_A16 - GPIO */
	PAD_CFG_GPO(GPP_A16, 0, DEEP),
	/* GPP_A17 - GPIO */
	PAD_CFG_GPO(GPP_A17, 0, DEEP),
	/* GPP_A18 - GPIO */
	PAD_CFG_GPO(GPP_A18, 0, DEEP),
	/* GPP_A19 - GPIO */
	PAD_CFG_GPO(GPP_A19, 0, DEEP),
	/* GPP_A20 - GPIO */
	PAD_CFG_GPO(GPP_A20, 0, DEEP),
	/* GPP_A21 - GPIO */
	PAD_CFG_GPO(GPP_A21, 0, DEEP),
	/* GPP_A22 - GPIO */
	PAD_CFG_GPO(GPP_A22, 0, DEEP),
	/* GPP_A23 - GPIO */
	PAD_CFG_GPO(GPP_A23, 0, DEEP),

	/* ------- GPIO Group GPP_B ------- */
	/* GPP_B0 - GPIO */
	PAD_CFG_GPO(GPP_B0, 0, DEEP),
	/* GPP_B1 - GPIO */
	PAD_CFG_GPO(GPP_B1, 0, DEEP),
	/* GPP_B2 - GPIO */
	PAD_CFG_GPO(GPP_B2, 1, DEEP),
	/* GPP_B3 - GPIO */
	PAD_CFG_GPO(GPP_B3, 0, DEEP),
	/* GPP_B4 - GPIO */
	PAD_CFG_GPO(GPP_B4, 0, DEEP),
	/* GPP_B5 - GPIO */
	PAD_CFG_GPO(GPP_B5, 1, PLTRST),
	/* GPP_B6 - GPIO */
	PAD_CFG_GPO(GPP_B6, 1, PLTRST),
	/* GPP_B7 - SRCCLKREQ2# */
	_PAD_CFG_STRUCT(GPP_B7,
		PAD_FUNC(NF1) | PAD_RESET(DEEP) |
		PAD_CFG0_TRIG_OFF | PAD_CFG0_RX_POL_NONE |
		PAD_BUF(TX_RX_DISABLE) | 1,
		PAD_PULL(NONE)),
	/* GPP_B8 - GPIO */
	PAD_CFG_GPO(GPP_B8, 1, PLTRST),
	/* GPP_B9 - GPIO */
	PAD_CFG_GPO(GPP_B9, 0, PLTRST),
	/* GPP_B10 - GPIO */
	PAD_CFG_GPO(GPP_B10, 0, PLTRST),
	/* GPP_B11 - GPIO */
	PAD_CFG_GPO(GPP_B11, 0, DEEP),
	/* GPP_B12 - GPIO */
	PAD_CFG_GPO(GPP_B12, 0, DEEP),
	/* GPP_B13 - PLTRST# */
	PAD_CFG_NF_BUF_TRIG(GPP_B13, NONE, DEEP, NF1, RX_DISABLE, OFF),
	/* GPP_B14 - GPIO */
	PAD_CFG_GPO(GPP_B14, 0, DEEP),
	/* GPP_B15 - GPIO */
	PAD_CFG_GPO(GPP_B15, 0, DEEP),
	/* GPP_B16 - GPIO */
	PAD_CFG_GPO(GPP_B16, 0, DEEP),
	/* GPP_B17 - GPIO */
	PAD_CFG_GPO(GPP_B17, 0, DEEP),
	/* GPP_B18 - GPIO */
	PAD_CFG_GPO(GPP_B18, 0, DEEP),
	/* GPP_B19 - GPIO */
	PAD_CFG_GPO(GPP_B19, 0, DEEP),
	/* GPP_B20 - GPIO */
	PAD_CFG_GPO(GPP_B20, 0, DEEP),
	/* GPP_B21 - GPIO */
	PAD_CFG_GPO(GPP_B21, 0, DEEP),
	/* GPP_B22 - GPIO */
	PAD_CFG_GPO(GPP_B22, 0, DEEP),
	/* GPP_B23 - GPIO */
	PAD_CFG_GPO(GPP_B23, 0, DEEP),

	/* ------- GPIO Community 1 ------- */

	/* ------- GPIO Group GPP_C ------- */
	/* GPP_C0 - SMBCLK */
	PAD_CFG_NF_BUF_TRIG(GPP_C0, NONE, DEEP, NF1, TX_DISABLE, OFF),
	/* GPP_C1 - SMBDATA */
	PAD_CFG_NF_BUF_TRIG(GPP_C1, NONE, DEEP, NF1, TX_DISABLE, OFF),
	/* GPP_C2 - GPIO */
	PAD_CFG_GPO(GPP_C2, 1, PLTRST),
	/* GPP_C3 - SML0CLK */
	PAD_CFG_NF_BUF_TRIG(GPP_C3, NONE, DEEP, NF1, TX_DISABLE, OFF),
	/* GPP_C4 - SML0DATA */
	PAD_CFG_NF_BUF_TRIG(GPP_C4, NONE, DEEP, NF1, TX_DISABLE, OFF),
	/* GPP_C5 - GPIO */
	PAD_CFG_GPO(GPP_C5, 0, DEEP),
	/* GPP_C6 - RESERVED */
	/* GPP_C7 - RESERVED */
	/* GPP_C8 - GPIO */
	PAD_CFG_GPO(GPP_C8, 0, DEEP),
	/* GPP_C9 - GPIO */
	PAD_CFG_GPO(GPP_C9, 0, DEEP),
	/* GPP_C10 - GPIO */
	PAD_CFG_GPO(GPP_C10, 0, DEEP),
	/* GPP_C11 - GPIO */
	PAD_CFG_GPO(GPP_C11, 0, DEEP),
	/* GPP_C12 - GPIO */
	PAD_CFG_GPO(GPP_C12, 0, DEEP),
	/* GPP_C13 - GPIO */
	PAD_CFG_GPO(GPP_C13, 0, DEEP),
	/* GPP_C14 - GPIO */
	PAD_CFG_GPO(GPP_C14, 0, DEEP),
	/* GPP_C15 - GPIO */
	PAD_CFG_GPO(GPP_C15, 0, DEEP),
	/* GPP_C16 - GPIO */
	PAD_CFG_GPO(GPP_C16, 0, DEEP),
	/* GPP_C17 - GPIO */
	PAD_CFG_GPO(GPP_C17, 0, DEEP),
	/* GPP_C18 - GPIO */
	PAD_CFG_GPO(GPP_C18, 0, DEEP),
	/* GPP_C19 - GPIO */
	PAD_CFG_GPO(GPP_C19, 0, DEEP),
	/* GPP_C20 - GPIO */
	PAD_CFG_GPO(GPP_C20, 0, DEEP),
	/* GPP_C21 - GPIO */
	PAD_CFG_GPO(GPP_C21, 0, DEEP),
	/* GPP_C22 - GPIO */
	PAD_CFG_GPO(GPP_C22, 0, DEEP),
	/* GPP_C23 - GPIO */
	PAD_CFG_GPO(GPP_C23, 0, DEEP),

	/* ------- GPIO Group GPP_D ------- */
	/* GPP_D0 - GPIO */
	PAD_CFG_GPO(GPP_D0, 0, DEEP),
	/* GPP_D1 - GPIO */
	PAD_CFG_GPO(GPP_D1, 0, DEEP),
	/* GPP_D2 - GPIO */
	PAD_CFG_GPO(GPP_D2, 0, DEEP),
	/* GPP_D3 - GPIO */
	PAD_CFG_GPO(GPP_D3, 0, DEEP),
	/* GPP_D4 - GPIO */
	PAD_CFG_GPO(GPP_D4, 0, DEEP),
	/* GPP_D5 - GPIO */
	PAD_CFG_GPO(GPP_D5, 0, DEEP),
	/* GPP_D6 - GPIO */
	PAD_CFG_GPO(GPP_D6, 0, DEEP),
	/* GPP_D7 - GPIO */
	PAD_CFG_GPO(GPP_D7, 0, DEEP),
	/* GPP_D8 - GPIO */
	PAD_CFG_GPO(GPP_D8, 0, DEEP),
	/* GPP_D9 - GPIO */
	PAD_CFG_GPO(GPP_D9, 0, DEEP),
	/* GPP_D10 - GPIO */
	PAD_CFG_GPO(GPP_D10, 0, DEEP),
	/* GPP_D11 - GPIO */
	PAD_CFG_GPO(GPP_D11, 0, DEEP),
	/* GPP_D12 - GPIO */
	PAD_CFG_GPO(GPP_D12, 0, DEEP),
	/* GPP_D13 - GPIO */
	PAD_CFG_GPO(GPP_D13, 0, DEEP),
	/* GPP_D14 - GPIO */
	PAD_CFG_GPO(GPP_D14, 0, DEEP),
	/* GPP_D15 - GPIO */
	PAD_CFG_GPO(GPP_D15, 0, DEEP),
	/* GPP_D16 - GPIO */
	PAD_CFG_GPO(GPP_D16, 0, DEEP),
	/* GPP_D17 - GPIO */
	PAD_CFG_GPO(GPP_D17, 0, DEEP),
	/* GPP_D18 - GPIO */
	PAD_CFG_GPO(GPP_D18, 0, DEEP),
	/* GPP_D19 - GPIO */
	PAD_CFG_GPO(GPP_D19, 0, DEEP),
	/* GPP_D20 - GPIO */
	PAD_CFG_GPO(GPP_D20, 0, DEEP),
	/* GPP_D21 - GPIO */
	PAD_CFG_GPO(GPP_D21, 0, DEEP),
	/* GPP_D22 - GPIO */
	PAD_CFG_GPO(GPP_D22, 0, DEEP),
	/* GPP_D23 - GPIO */
	PAD_CFG_GPO(GPP_D23, 0, DEEP),

	/* ------- GPIO Group GPP_E ------- */
	/* GPP_E0 - SATAXPCIE0 */
	PAD_CFG_NF_BUF_TRIG(GPP_E0, 20K_PU, PLTRST, NF1, TX_DISABLE, OFF),
	/* GPP_E1 - GPIO */
	PAD_CFG_GPO(GPP_E1, 0, DEEP),
	/* GPP_E2 - GPIO */
	PAD_CFG_GPO(GPP_E2, 0, DEEP),
	/* GPP_E3 - GPIO */
	PAD_CFG_GPO(GPP_E3, 0, DEEP),
	/* GPP_E4 - GPIO */
	PAD_CFG_GPO(GPP_E4, 0, DEEP),
	/* GPP_E5 - GPIO */
	PAD_CFG_GPO(GPP_E5, 0, DEEP),
	/* GPP_E6 - GPIO */
	PAD_CFG_GPO(GPP_E6, 0, DEEP),
	/* GPP_E7 - GPIO */
	PAD_CFG_GPO(GPP_E7, 0, DEEP),
	/* GPP_E8 - SATA_LED# */
	PAD_CFG_NF_BUF_TRIG(GPP_E8, NONE, PLTRST, NF1, RX_DISABLE, OFF),
	/* GPP_E9 - USB_OC0# */
	PAD_CFG_NF_BUF_TRIG(GPP_E9, NONE, DEEP, NF1, TX_DISABLE, OFF),
	/* GPP_E10 - USB_OC1# */
	PAD_CFG_NF_BUF_TRIG(GPP_E10, NONE, DEEP, NF1, TX_DISABLE, OFF),
	/* GPP_E11 - USB_OC2# */
	PAD_CFG_NF_BUF_TRIG(GPP_E11, NONE, DEEP, NF1, TX_DISABLE, OFF),
	/* GPP_E12 - USB_OC3# */
	PAD_CFG_NF_BUF_TRIG(GPP_E12, NONE, DEEP, NF1, TX_DISABLE, OFF),

	/* ------- GPIO Group GPP_F ------- */
	/* GPP_F0 - GPIO */
	PAD_CFG_GPO(GPP_F0, 0, DEEP),
	/* GPP_F1 - GPIO */
	PAD_CFG_GPO(GPP_F1, 0, DEEP),
	/* GPP_F2 - GPIO */
	PAD_CFG_GPO(GPP_F2, 0, DEEP),
	/* GPP_F3 - GPIO */
	PAD_CFG_GPO(GPP_F3, 0, DEEP),
	/* GPP_F4 - GPIO */
	PAD_CFG_GPO(GPP_F4, 0, DEEP),
	/* GPP_F5 - GPIO */
	PAD_CFG_GPO(GPP_F5, 0, DEEP),
	/* GPP_F6 - GPIO */
	PAD_CFG_GPO(GPP_F6, 0, DEEP),
	/* GPP_F7 - GPIO */
	PAD_CFG_GPO(GPP_F7, 0, DEEP),
	/* GPP_F8 - GPIO */
	PAD_CFG_GPO(GPP_F8, 0, DEEP),
	/* GPP_F9 - GPIO */
	PAD_CFG_GPO(GPP_F9, 0, DEEP),
	/* GPP_F10 - GPIO */
	PAD_CFG_GPO(GPP_F10, 0, DEEP),
	/* GPP_F11 - GPIO */
	PAD_CFG_GPO(GPP_F11, 0, DEEP),
	/* GPP_F12 - GPIO */
	PAD_CFG_GPO(GPP_F12, 0, DEEP),
	/* GPP_F13 - GPIO */
	PAD_CFG_GPO(GPP_F13, 0, DEEP),
	/* GPP_F14 - GPIO */
	PAD_CFG_GPO(GPP_F14, 0, DEEP),
	/* GPP_F15 - USB_OC4# */
	PAD_CFG_NF_BUF_TRIG(GPP_F15, NONE, DEEP, NF1, TX_DISABLE, OFF),
	/* GPP_F16 - USB_OC5# */
	PAD_CFG_NF_BUF_TRIG(GPP_F16, NONE, DEEP, NF1, TX_DISABLE, OFF),
	/* GPP_F17 - USB_OC6# */
	PAD_CFG_NF_BUF_TRIG(GPP_F17, NONE, DEEP, NF1, TX_DISABLE, OFF),
	/* GPP_F18 - USB_OC7# */
	PAD_CFG_NF_BUF_TRIG(GPP_F18, NONE, DEEP, NF1, TX_DISABLE, OFF),
	/* GPP_F19 - GPIO */
	PAD_CFG_GPO(GPP_F19, 0, DEEP),
	/* GPP_F20 - GPIO */
	PAD_CFG_GPO(GPP_F20, 0, DEEP),
	/* GPP_F21 - GPIO */
	PAD_CFG_GPO(GPP_F21, 0, DEEP),
	/* GPP_F22 - GPIO */
	PAD_CFG_GPO(GPP_F22, 1, PLTRST),
	/* GPP_F23 - GPIO */
	PAD_CFG_GPO(GPP_F23, 0, DEEP),

	/* ------- GPIO Group GPP_G ------- */
	/* GPP_G0 - GPIO */
	PAD_CFG_GPO(GPP_G0, 0, PLTRST),
	/* GPP_G1 - GPIO */
	PAD_CFG_GPO(GPP_G1, 0, DEEP),
	/* GPP_G2 - GPIO */
	PAD_CFG_GPO(GPP_G2, 0, DEEP),
	/* GPP_G3 - GPIO */
	PAD_CFG_GPO(GPP_G3, 0, DEEP),
	/* GPP_G4 - GPIO */
	PAD_CFG_GPO(GPP_G4, 0, DEEP),
	/* GPP_G5 - GPIO */
	PAD_CFG_GPO(GPP_G5, 0, DEEP),
	/* GPP_G6 - GPIO */
	PAD_CFG_GPO(GPP_G6, 0, DEEP),
	/* GPP_G7 - GPIO */
	PAD_CFG_GPO(GPP_G7, 0, DEEP),
	/* GPP_G8 - GPIO */
	PAD_CFG_GPO(GPP_G8, 0, PLTRST),
	/* GPP_G9 - GPIO */
	PAD_CFG_GPO(GPP_G9, 0, DEEP),
	/* GPP_G10 - GPIO */
	PAD_CFG_GPO(GPP_G10, 0, DEEP),
	/* GPP_G11 - GPIO */
	PAD_CFG_GPO(GPP_G11, 0, DEEP),
	/* GPP_G12 - GPIO */
	PAD_CFG_GPO(GPP_G12, 0, DEEP),
	/* GPP_G13 - GPIO */
	PAD_CFG_GPO(GPP_G13, 0, DEEP),
	/* GPP_G14 - GPIO */
	PAD_CFG_GPO(GPP_G14, 0, DEEP),
	/* GPP_G15 - GPIO */
	PAD_CFG_GPO(GPP_G15, 0, DEEP),
	/* GPP_G16 - GPIO */
	PAD_CFG_GPO(GPP_G16, 0, DEEP),
	/* GPP_G17 - GPIO */
	PAD_CFG_GPO(GPP_G17, 0, DEEP),
	/* GPP_G18 - GPIO */
	PAD_CFG_GPO(GPP_G18, 0, DEEP),
	/* GPP_G19 - GPIO */
	PAD_CFG_GPO(GPP_G19, 1, PLTRST),
	/* GPP_G20 - GPIO */
	PAD_CFG_GPO(GPP_G20, 0, DEEP),
	/* GPP_G21 - GPIO */
	PAD_CFG_GPO(GPP_G21, 0, DEEP),
	/* GPP_G22 - GPIO */
	PAD_CFG_GPO(GPP_G22, 0, DEEP),
	/* GPP_G23 - GPIO */
	PAD_CFG_GPO(GPP_G23, 0, DEEP),

	/* ------- GPIO Group GPP_H ------- */
	/* GPP_H0 - GPIO */
	PAD_CFG_GPO(GPP_H0, 0, DEEP),
	/* GPP_H1 - GPIO */
	PAD_CFG_GPO(GPP_H1, 0, DEEP),
	/* GPP_H2 - GPIO */
	PAD_CFG_GPO(GPP_H2, 0, DEEP),
	/* GPP_H3 - GPIO */
	PAD_CFG_GPO(GPP_H3, 0, DEEP),
	/* GPP_H4 - GPIO */
	PAD_CFG_GPO(GPP_H4, 0, DEEP),
	/* GPP_H5 - GPIO */
	PAD_CFG_GPO(GPP_H5, 0, DEEP),
	/* GPP_H6 - GPIO */
	PAD_CFG_GPO(GPP_H6, 0, DEEP),
	/* GPP_H7 - GPIO */
	PAD_CFG_GPO(GPP_H7, 0, DEEP),
	/* GPP_H8 - GPIO */
	PAD_CFG_GPO(GPP_H8, 0, DEEP),
	/* GPP_H9 - GPIO */
	PAD_CFG_GPO(GPP_H9, 0, DEEP),
	/* GPP_H10 - GPIO */
	PAD_CFG_GPO(GPP_H10, 0, DEEP),
	/* GPP_H11 - GPIO */
	PAD_CFG_GPO(GPP_H11, 0, DEEP),
	/* GPP_H12 - GPIO */
	PAD_CFG_GPO(GPP_H12, 0, DEEP),
	/* GPP_H13 - GPIO */
	PAD_CFG_GPO(GPP_H13, 0, DEEP),
	/* GPP_H14 - GPIO */
	PAD_CFG_GPO(GPP_H14, 0, DEEP),
	/* GPP_H15 - GPIO */
	PAD_CFG_GPO(GPP_H15, 0, DEEP),
	/* GPP_H16 - GPIO */
	PAD_CFG_GPO(GPP_H16, 0, DEEP),
	/* GPP_H17 - GPIO */
	PAD_CFG_GPO(GPP_H17, 0, DEEP),
	/* GPP_H18 - GPIO */
	PAD_CFG_GPO(GPP_H18, 0, DEEP),
	/* GPP_H19 - GPIO */
	PAD_CFG_GPO(GPP_H19, 0, DEEP),
	/* GPP_H20 - GPIO */
	PAD_CFG_GPO(GPP_H20, 0, DEEP),
	/* GPP_H21 - GPIO */
	PAD_CFG_GPO(GPP_H21, 0, DEEP),
	/* GPP_H22 - GPIO */
	PAD_CFG_GPO(GPP_H22, 0, DEEP),
	/* GPP_H23 - GPIO */
	PAD_CFG_GPO(GPP_H23, 0, DEEP),

	/* ------- GPIO Community 2 ------- */

	/* -------- GPIO Group GPD -------- */
	/* GPD0 - GPIO */
	PAD_CFG_GPO(GPD0, 1, PWROK),
	/* GPD1 - GPIO */
	PAD_CFG_GPO(GPD1, 0, PWROK),
	/* GPD2 - LAN_WAKE# */
	PAD_CFG_NF_BUF_TRIG(GPD2, NATIVE, PWROK, NF1, TX_DISABLE, LEVEL),
	/* GPD3 - PWRBTN# */
	PAD_CFG_NF_BUF_TRIG(GPD3, 20K_PU, PWROK, NF1, TX_DISABLE, OFF),
	/* GPD4 - SLP_S3# */
	PAD_CFG_NF_BUF_TRIG(GPD4, NONE, PWROK, NF1, RX_DISABLE, OFF),
	/* GPD5 - SLP_S4# */
	PAD_CFG_NF_BUF_TRIG(GPD5, NONE, PWROK, NF1, RX_DISABLE, OFF),
	/* GPD6 - SLP_A# */
	PAD_CFG_NF_BUF_TRIG(GPD6, NONE, PWROK, NF1, RX_DISABLE, OFF),
	/* GPD7 - GPIO */
	PAD_CFG_GPO(GPD7, 0, PWROK),
	/* GPD8 - GPIO */
	PAD_CFG_GPO(GPD8, 0, PWROK),
	/* GPD9 - GPIO */
	PAD_CFG_GPO(GPD9, 1, PWROK),
	/* GPD10 - SLP_S5# */
	PAD_CFG_NF_BUF_TRIG(GPD10, NONE, PWROK, NF1, RX_DISABLE, OFF),
	/* GPD11 - LANPHYPC */
	PAD_CFG_NF_BUF_TRIG(GPD11, NONE, PWROK, NF1, RX_DISABLE, OFF),

	/* ------- GPIO Community 3 ------- */

	/* ------- GPIO Group GPP_I ------- */
	/* GPP_I0 - DDPB_HPD0 */
	PAD_CFG_NF_BUF_TRIG(GPP_I0, NONE, PLTRST, NF1, TX_DISABLE, OFF),
	/* GPP_I1 - DDPC_HPD1 */
	PAD_CFG_NF_BUF_TRIG(GPP_I1, NONE, PLTRST, NF1, TX_DISABLE, OFF),
	/* GPP_I2 - DDPD_HPD2 */
	PAD_CFG_NF_BUF_TRIG(GPP_I2, NONE, PLTRST, NF1, TX_DISABLE, OFF),
	/* GPP_I3 - GPIO */
	PAD_CFG_GPO(GPP_I3, 0, DEEP),
	/* GPP_I4 - GPIO */
	PAD_CFG_GPO(GPP_I4, 0, PLTRST),
	/* GPP_I5 - DDPB_CTRLCLK */
	PAD_CFG_NF_BUF_TRIG(GPP_I5, NONE, PLTRST, NF1, TX_DISABLE, OFF),
	/* GPP_I6 - DDPB_CTRLDATA */
	PAD_CFG_NF_BUF_TRIG(GPP_I6, 20K_PD, PLTRST, NF1, TX_DISABLE, OFF),
	/* GPP_I7 - DDPC_CTRLCLK */
	PAD_CFG_NF_BUF_TRIG(GPP_I7, NONE, PLTRST, NF1, TX_DISABLE, OFF),
	/* GPP_I8 - DDPC_CTRLDATA */
	PAD_CFG_NF_BUF_TRIG(GPP_I8, 20K_PD, PLTRST, NF1, TX_DISABLE, OFF),
	/* GPP_I9 - DDPD_CTRLCLK */
	PAD_CFG_NF_BUF_TRIG(GPP_I9, NONE, PLTRST, NF1, TX_DISABLE, OFF),
	/* GPP_I10 - DDPD_CTRLDATA */
	PAD_CFG_NF_BUF_TRIG(GPP_I10, 20K_PD, PLTRST, NF1, TX_DISABLE, OFF),
};
/* Early pad configuration in romstage. */
static const struct pad_config early_gpio_table[] = {
	/* TODO: Add early pad configuration */
};

#endif
